---
title: "Computational Programming for the Social Sciences"
author: "Sarah Moore and Jean Clipperton"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::bs4_book
documentclass: book
biblio-style: apalike
link-citations: yes
description: "A guide to thinking about data and analysis in R and Python for students of the social sciences."
---

# Welcome!{#ch1}

This text is a guide to thinking about data and its analysis in R and Python for students of the social sciences. Included in this text are elementary introductions into computational programming languages that are useful for performing data management and quantitative statistical analyses. This text should serve as a companion to our main text: *Introductory Probability and Statistics for Social Sciences*.

These texts are jointly authored by Jean Clipperton and Sarah Moore to serve in the Northwestern University Political Science and Sociology graduate student methodological curriculum. To develop these texts and the graduate student curriculum, we have relied on some core sources:

[YaRrr! The Pirate’s Guide to R](https://bookdown.org/ndphillips/YaRrr/projects-in-rstudio.html) by Nathaniel Phillips 

[Advanced R](http://adv-r.had.co.nz/Introduction.html), First and Second Editions by Hadley Wickham 

[ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/index.html) by Hadley Wickham 

[Yihui Xie's *bookdown: Authoring Books and Technical Documents with R Markdown*](https://bookdown.org/yihui/bookdown/)

[Sean Kross's guide to `bookdown`](https://seankross.com/2016/11/17/How-to-Start-a-Bookdown-Book.html)



## Requirements

As a prerequisite, the tutorials in this text require that you download [R](https://cran.r-project.org/), [RStudio IDE](https://www.rstudio.com/), [Python](https://www.python.org/downloads/), and [PyCharm](https://www.jetbrains.com/pycharm/) to interface with the pertinent coding languages-- R and Python. Later sections will go into more detail regarding how to load and interact with these programs on your computer, but please ensure that you have sufficient storage and computing power to operate these programs.

Additional activities will require that you become familiar with [GitHub](https://github.com/), [LaTeX](https://www.latex-project.org/), and additional computational packages that are downloaded *ad hoc* in their respective programming platform.

We further suggest that you familiarize yourself with [StackExchange](https://stackexchange.com/) or [StackOverflow](https://stackoverflow.com/). Stack sites host incredibly helpful message boards for troubleshooting problems related to really anything, but here we emphasize their usefulness for questions related to statistics and programming. It's likely that one of your many questions you will have are already answered on Stack!

## Questions or Comments

This text is updated regularly and we welcome all suggestions toward its improvement. Please email one of the authors, [Sarah Moore](mailto:sarahmoore2022@u.northwestern.edu) or [Jean Clipperton](mailto:jean.clipperton@northwestern.edu), with your comments.
