---
author: "NAME"
date: "DATE"
output: pdf_document
header-includes: 
 - \usepackage{amsmath}
 - \usepackage{amsfonts}
 - \usepackage{amssymb}
 - \usepackage{amsthm}
 - \usepackage{graphicx}
 - \usepackage{setspace}
 - \usepackage{fullpage}
 - \usepackage{color}
 - \usepackage{comment}
 - \usepackage{bm}
 - \usepackage{url}
 - \usepackage{hyperref}
 - \usepackage{color,hyperref}
 - \definecolor{darkblue}{rgb}{0.0,0.0,0.3}
 - \hypersetup{colorlinks,breaklinks,
            linkcolor=darkblue,urlcolor=darkblue,
            anchorcolor=darkblue,citecolor=darkblue}
---
#Problem Set 2 - PS & SOC Math Prefresher

*NAME HERE* 
 
Include all your work. You can do this by hand or type it up in R markdown. Your choice as long as it's readable. 

Due start of class on Day 5. 

\begin{enumerate}
\item Summation
\begin{enumerate}
\item $\sum_{n=1}^{7}3$
\item $\sum_{n=0}^{4} 2n+8$
\end{enumerate}

\item Limits and Continuity
\begin{enumerate}
\item Graph $x^2+2$ and plot the tangent line at $x=0$. 
\item What is a limit?
\item Why do we care about limits and tangents?
\item What is a continuous function?
\end{enumerate}

\item Set theory
\begin{enumerate}
\item In roster notation, write the set characterized in set-builder notation as $S = \{x \in \mathbb{Z}, 2 <x <5\}$.
\item Is the following statement True or False? $\forall x \in S, x\geq 2$ for $S = \{3,2,5,9\}$.
\item Is the following statement True or False? $\exists x \in S\; s.t. \; x \notin \mathbb{Z}$ for $S = \{3,2,5,9\}$.
\item Is $\{1,2,3,4\}$ a subset of $\{4,3,1,2\}$? Is it a proper subset?
\item Using logical symbols (including $\exists$ and $\forall$) write the definition of a proper subset.
\item If $A = \{soup, 8\}$ and $B = \{x, soup\}$ find $A \cup B$.
\item (Follow-up): Now find $A \cap B$.
\item (Follow-up): Find the Cartesian Product $A \times B$.
\end{enumerate}

\item Review:
\begin{enumerate}
\item Write out `6 choose 3' mathematically and solve.
\item Add these two matrices: $
\begin{bmatrix}
   2 & 4 & 2 \\
    1 & 4 & 0 \\
    2 & 6 & 0
\end{bmatrix}
+
\begin{bmatrix}
5 & 1 & 1 \\
2 & 2 & 2\\
4 & 1 & 3
\end{bmatrix}
$

\item Multiply these two matrices: $
\begin{bmatrix}
   2 & 4 & 2 \\
    1 & 4 & 0 \\
    2 & 6 & 0
\end{bmatrix}
*
\begin{bmatrix}
5 & 1 & 1 \\
2 & 2 & 2 \\
4 & 1 & 3
\end{bmatrix}
$
\item Provide an example matrix, showing what happens when you multiply by the identity matrix. 
\item List three things you struggled with on yesterday's assignment. 
\item What is your plan for improving the items listed above?
\end{enumerate}

\end{enumerate}




