---
title: "Problem Set 4" 
author: "NAME"
date: "DATE"
output: pdf_document
header-includes: 
- \usepackage{amsmath}
- \usepackage{amsfonts}
- \usepackage{amssymb}
- \usepackage{amsthm}
- \usepackage{graphicx}
- \usepackage{setspace}
- \usepackage{fullpage}
- \usepackage{color}
- \usepackage{comment}
- \usepackage{bm}
- \usepackage{url}
- \usepackage{hyperref}
- \usepackage{color,hyperref}
- \definecolor{darkblue}{rgb}{0.0,0.0,0.3}
- \hypersetup{colorlinks,breaklinks,
            linkcolor=darkblue,urlcolor=darkblue,
            anchorcolor=darkblue,citecolor=darkblue}
---
\maketitle 

Due at close of business Day 10. 

\begin{enumerate}
\item Integrals: Foundations
\begin{enumerate}

\item What is an integral (e.g. what does it do?)
\item Why would we use an integral?
\item Calculate the area under $x^3$ on $[1,4]$ using rectangles. 
\item (Follow up) Now, calculate the area a second time using smaller rectangles. 
\item (Follow up) How do these areas compare? How does your finding here relate to the definition of an integral (above)?
\end{enumerate}


\item Integration Practice: Calculate the definite integrals for the following
\begin{enumerate}
\item $\int_1^4 x^3 dx$
\item $\int_0^3 x dx$
\item $\int_1^4 (6x^3-2) dx$
\item $\int_4^6 x dx$
\item $\int_0^y (e^x-2x^2)dx$
\end{enumerate}


\item Iterated Integration Practice: Calculate the following
\begin{enumerate}
\item $\int_1^4  \int_0^2 (6x^3-2y)$ \textit{dx dy}
\item $\int_0^1 \int_1^x 3x-4$ \textit{dy dx}
\item $\int_0^1 \int_1^y 3x-4$ \textit{dx dy}
\end{enumerate}

\item Probability and Statistics 
  \begin{enumerate}
    \item Provide one example of an event or set of events that fulfill the following conditions and one that does not: 
      \begin{itemize}
        \item Independence
        \item Mutual Exclusivity 
        \item Collective Exhaustion
      \end{itemize}
    \item Provide an example of a discrete random variable. Create an example histogram of the distribution of this random variable with fake data. 
    \item Provide an example of a continuous random variable. 
  \end{enumerate}
\item Topics and Questions
    \begin{enumerate}
        \item List three things you struggled with on today's assignment. 
        \item What is your plan for improving the items listed above?
        \item What percent of the material was new to you today?
        \item What is one new concept you learned today?
        \item What question do you still have about the material?
    \end{enumerate}

\end{enumerate}
